% g(nu) Eq.50
% Ruohai Guo
% e-mail: rhguo@zju.edu.cn
% Date: 2025. 05. 19

function KKT_nu = nu_picture(nu,y1_tilde,y2_tilde,sigma,sigma_e,sigma_n,m,y2_tilde_norm)
if isnan(y2_tilde)
    KKT_nu = sum(abs(y1_tilde) .^ 2 - abs(y1_tilde) .^ 2 .*sigma .^ 2 ./...
            (sigma .^ 2 + 2 * nu * sigma_e),'all') + y2_tilde_norm - ...
            m * (sum(sigma_e * abs(y1_tilde) .^ 2 .*sigma .^ 2 ./ ...
            (sigma .^ 2 + 2 * nu * sigma_e).^2 ,"all") + sigma_n) + 2 * nu *sigma_n;
        
else
    KKT_nu = sum(y1_tilde.^ 2 * nu ./ ...
            (sigma .^ 2 / sigma_e + 2 * nu),'all') + norm(y2_tilde)^2 / 2 - ...
            m / 2 * (sum(sigma_e * y1_tilde.^ 2 .*sigma .^ 2 ./ ...
            (sigma .^ 2 + 2 * nu * sigma_e).^2 ,"all") + sigma_n) + ...
            nu * sigma_n;

end
if abs(KKT_nu) < 1e-15
    KKT_nu = 0;
end
